int x0 = 0;
int x1 = 1;
int y0 = 2;
int y1 = 3;
int y2 = 4;
int rw = 5;
int lw = 6;
int dw = 7;
int uw = 8;
int t1 = A4;
int t2 = A3;
int t3 = A2;
int done = A1;
int valid = A0; 

void setup() {
  // put your setup code here, to run once:
  pinMode(x0,OUTPUT);
  pinMode(x1,OUTPUT);
  pinMode(y0,OUTPUT);
  pinMode(y1,OUTPUT);
  pinMode(y2,OUTPUT);
  pinMode(rw,OUTPUT);
  pinMode(lw,OUTPUT);
  pinMode(dw,OUTPUT);
  pinMode(uw,OUTPUT);
  pinMode(t1,OUTPUT);
  pinMode(t2,OUTPUT);
  pinMode(t3,OUTPUT);
  pinMode(done,OUTPUT);
  pinMode(valid,OUTPUT);
}

void loop() {
  digitalWrite(x0,LOW);
  digitalWrite(x1,LOW);
  digitalWrite(y0,LOW);
  digitalWrite(y1,LOW);
  digitalWrite(y2,LOW);
  digitalWrite(rw,LOW);
  digitalWrite(lw,HIGH);
  digitalWrite(dw,LOW);
  digitalWrite(uw,LOW);
  digitalWrite(t1,LOW);
  digitalWrite(t2,LOW);
  digitalWrite(t3,LOW);
  digitalWrite(done,LOW);
  digitalWrite(valid,LOW);
  delay(1000);
  digitalWrite(valid,HIGH);
  delay(100);
  digitalWrite(valid,LOW);
  delay(1000);  
  digitalWrite(y0,HIGH);
  digitalWrite(valid,HIGH);
  delay(100);
  digitalWrite(valid,LOW);
  delay(1000);
  digitalWrite(y0,LOW);
  digitalWrite(y1,HIGH);
  digitalWrite(rw,HIGH);
  digitalWrite(valid,HIGH);
  delay(100);
  digitalWrite(valid,LOW);
  delay(1000);
  digitalWrite(y0,HIGH);
  digitalWrite(valid,HIGH);
  delay(100);
  digitalWrite(valid,LOW);
  delay(1000);
  digitalWrite(y1,LOW);
  digitalWrite(y0,LOW);
  digitalWrite(y2,HIGH); 
  digitalWrite(uw,HIGH);
  digitalWrite(valid,HIGH);
  delay(100);
  digitalWrite(valid,LOW);
  delay(1000);
  digitalWrite(uw,LOW);
  digitalWrite(y2,LOW);
  digitalWrite(y1,HIGH);
  digitalWrite(y0,HIGH);
  digitalWrite(valid,HIGH);
  delay(100);
  digitalWrite(valid,LOW);
  delay(1000);
  digitalWrite(y0,LOW);
  digitalWrite(valid,HIGH);
  delay(100);
  digitalWrite(valid,LOW);
  delay(1000);
  digitalWrite(y1,LOW);
  digitalWrite(y0,HIGH);
  digitalWrite(rw,LOW);
  digitalWrite(valid,HIGH);
  delay(100);
  digitalWrite(valid,LOW);
  delay(1000);
  digitalWrite(x0,HIGH);
  digitalWrite(lw,LOW);
  digitalWrite(uw,HIGH);
  digitalWrite(rw,HIGH);
  digitalWrite(valid,HIGH);
  delay(100);
  digitalWrite(valid,LOW);
  delay(1000);
  digitalWrite(y0,LOW);
  digitalWrite(uw,LOW);
  digitalWrite(dw,HIGH);
  digitalWrite(done,HIGH);
  digitalWrite(valid,HIGH);
  delay(100);
  digitalWrite(valid,LOW);
  delay(10000);
}
